### ISSUE TITLE
v9.6 .exe does not run on windows

### ISSUE THREAD

**Issue by saffman** [pairinteraction/pairinteraction#115]
Hi, I have been playing around with v9.5 executable on windows 10. Seems to work correctly for Cs ns states. When I try Cs d3/2 states I get zero interaction. Not sure if the mistake is me or the program. So I downloaded v9.6 executable which says it fixes bugs in radial matrix elements. However v9.6 doesn't run on windows.   The cmd window opens for a second then it shuts down again. 
Mark S.

**Comment by hmenke** [comment]
We apologize for this inconvenience.  In fact the crash was already reported in #108 and has been fixed in https://github.com/pairinteraction/pairinteraction/commit/7ee77d83d0a885e9fe2db234e9b451604377da71 but we haven't published a new release yet, which we definitely should have done.

In the meantime you can try the installer from here: https://ci.appveyor.com/api/buildjobs/klri39p631f3q6oe/artifacts/build%2Fpairinteraction-install-windows.exe

Could you also add some more detail on the problem with the d3/2 states, please?  Zero interaction doesn't sound right and I don't think that this is related to the fix for the radial elements that we introduced in 0.9.6.  So this might be a new bug.

**Comment by saffman** [comment]
The new installer works fine, thank you.

The zero interaction problem seems to have been my fault. I was looking at a case with weak interactions. When I enlarged the basis the interaction turned on. I’ll let you know if I find any real bugs.

Mark S.

**Comment by hmenke** [comment]
This is now fixed in the [0.9.7 release](https://github.com/pairinteraction/pairinteraction/releases/tag/v0.9.7-alpha). Thanks for reporting.
