### ISSUE TITLE
Magnetic dependance seems having some problems.

### ISSUE THREAD

**Issue by DanielYang2017** [pairinteraction/pairinteraction#65]
For example, with two atoms (Rb, n=43, l=2 ,j=3/2,m=1/2) interacting  with each other at R=10um and B=0 gauss, I can export the matlab data given by the problem, then I succeed in calculating the blockade shift given by Saffman, RMP.  
But when I set B as a small value(5 gauss), I got a totally chaos result, it's nothing seems  in accord with the results given by the RMP. So I think maybe the program have some Bugs.

**Comment by seweber** [comment]
Thank you for your request. I looked into it. However, I cannot reproduce your issue, every thing seems to work fine. Maybe, you have specified a wrong basis set?

In order to figure out what exactly caused the problem, I need additional information. For me, it would be helpful to know all the parameters you have chosen. You can export the parameters via "Configuration" / "Save system settings" in the menu bar. Which version of the pairinteraction software are you using?



However, I cannot reproduce this problem. Maybe, you have chosen the wrong

**Comment by DanielYang2017** [comment]
My operation in detail and Configuration are uploaded as attachment. And my software version is 0.6-alpha, Thanks for your response!

[detail.pdf](https://github.com/pairinteraction/pairinteraction/files/1142154/detail.pdf)

[config1.zip](https://github.com/pairinteraction/pairinteraction/files/1142156/config1.zip)

**Comment by seweber** [comment]
Thank you for your detailed notes. I think, I figured out the reason for the differences: The eigenenergies calculated by the pairinteraction program include the energy shifts due to the dipole-dipole interaction and electric and magnetic fields. Thus, in your case, you have to subtract the Zeeman shifts due to the magnetic field before applying equation (3) of the [paper by Saffman](https://journals.aps.org/rmp/pdf/10.1103/RevModPhys.82.2313). You can get the values of the Zeeman shifts by disabling the dipole-dipole interaction (this can be achieved by setting the "max. order" of the multipole expansion to a value smaller than 3).

Please let me know whether this helps to reproduce the Saffman results.

**Comment by DanielYang2017** [comment]
@seweber Thanks for your suggestion I managed to  reproduce the Saffman results of magnetic dependance after further exploration of  those values of the Zeeman shifts. But  instead of changing  "max. order" of the multipole expansion, I acquired the single atom field map and found that the energy of initial state is no longer set to be zero with B is nonzero, in another word the zero of energy is changed, so it's easily to calculate the correct relative energy shift after some compensation.

![figure](https://user-images.githubusercontent.com/30108183/28173725-de27f26c-6821-11e7-824c-3ce96a7c30f3.png)

**Comment by seweber** [comment]
Perfect. Thanks for the update. Changing "max. order" to a value smaller than tree would have directly produced the Zeeman map for the pair states. Maybe, we could include a GUI button to switch between different definitions of zero energy. Thereto, I opened a new issue #66.
