### ISSUE TITLE
python module files missing

### ISSUE THREAD

**Issue by mfe5003** [pairinteraction/pairinteraction#79]
I installed from source on ubuntu (using WSL on windows 10) and it looks like the python files are not populated in:
`$root_dir/pairinteration/libpairinteraction/`
which is where the documentation [here](https://pairinteraction.github.io/pairinteraction/sphinx/html/comparison_to_saffman_fig13.html) says to append to the python path.

I found the files in the build directory and appended the following to my path to get it to work:
`$root_dir/pairinteration/build/`

I'm guessing pointing at the build directory was the intended behavior and the documentation is old but  I don't know.

**Comment by hmenke** [comment]
Thank you very much for raising this issue.  So far we have not been targeting WSL explicitly.  The Linux subsystem for Windows is rather heterogeneous because you can use several different distributions as the base system so it might be a little difficult to make it reliably build on all possible platforms.  Unfortunately, both @seweber and me don't use Windows so it might take us a while to produce something usable.

**Comment by mfe5003** [comment]
I'm sorry, I copied the working include path wrong.  It should be:
`$root_dir/pairinteration/build/`
I will edit this in the original post.

I'll try installing from source on my actual linux machine later and see if the issue persists.

**Comment by seweber** [comment]
We have added some clarifications to the [installation docs](https://pairinteraction.github.io/pairinteraction/sphinx/html/installation.html):

> In the tutorials and examples you will often find instructions to extend the PYTHONPATH to accomodate pairinteraction. These instructions only hold true if you installed pairinteraction from the official binary installers. If you built from source you instead have to point the scripts to your build directory or the custom location where you installed the program.

I think, this closes the issue.
